name: Bug Report
description: Report if a bug has occurred.
body:
  - type: textarea
    attributes: 
      label: The problem
      description: Provide details of the bug, how to get the bug, etc.
      value: |
        <!-- 
          PLEASE READ:
          There are some know bugs:
            1. disappearing parts after save (see Issue #20)
            2. incomplete Live2D parts after loading

          These bugs are caused by the PIXI.js-Live2D Renderer library, not the application itself.
          Any issues created related to these bugs will be automatically closed.
        -->
        ### Decription 
        <!-- Describe the bug -->

        ### To produce the bug 
        <!-- A clear step by step instructions on how to reproduce the bug -->
    validations:
      required: true
  - type: textarea 
    attributes:
      label: Screenshot/Screen recording
      description: Add a screenshot or a screen recording of the bug
      placeholder: You can drag or drop the file here.
    validations:
      required: true
